### ISSUE TITLE
Update VSIX manifest with requirement for VS 2022 version

### ISSUE THREAD

**Issue by vuhuy** [AdaskoTheBeAsT/Typewriter#14]
The latest 2.8.0 release contains dependencies to specific binaries for Visual Studio 2022 v17.2. However when using a private gallery, the updated 2.8.0 will also install on clients with Visual Studio 2022 <17.2. Unfortunately, I updated my Visual Studio installation 2022 and lost the ActivityLog.xml.

However, the cause is quite obvious  by analysing this [commit](https://github.com/AdaskoTheBeAsT/Typewriter/commit/707db51d4091f7bc5f6aa7b36b7f2a6eca595706).

If possible, prevent installation via requirements in the package manifest.

**Comment by AdaskoTheBeAsT** [comment]
@vuhuy thanks for notifying that - I will update vsix manifest
