### ISSUE TITLE
Version 2.9.0 not working with Visual Studio 22 (Version 17.3.1)

### ISSUE THREAD

**Issue by co-dax** [AdaskoTheBeAsT/Typewriter#16]
Hey, great work!

As stated in the title, version 2.9.0 is not working with Visual Studio 22 (Version 17.3.1). When I open .tst file I don't see syntax highlighting at all while it was there in VS 2019. When saving it doesn't work either, nothig happens when I save .cs files the used to produced usual result in VS 2019.

Please let me know what other how I can provide more details.

Thanks!

**Comment by AdaskoTheBeAsT** [comment]
Hi i will take a look

czw., 18 sie 2022, 01:12 użytkownik co-dax ***@***.***>
napisał:

**Comment by co-dax** [comment]
Thanks!

**Comment by co-dax** [comment]
Hey, I tried re-installing the plugin and it just works after that. I don't know what happened but it works.

Thanks!
