### ISSUE TITLE
EnvDTE.DTE not found anymore

### ISSUE THREAD

**Issue by nfMalde** [AdaskoTheBeAsT/Typewriter#2]
Hi!
Ive tested your vs22 build and after the switch Im not able to use EnvDTE.DTE anymore...

```
#reference EnvDTE 
#reference Microsoft.VisualStudio.Shell.15.0
```

```
EnvDTE.DTE dte = (EnvDTE.DTE)Microsoft.VisualStudio.Shell.Package.GetGlobalService(typeof(EnvDTE.DTE));

```
Im using this to get the full soulution path.

Works fine in 1.2 for VS2019 (official). Anything changed regarding the API?

Best,

Malte

**Comment by AdaskoTheBeAsT** [comment]
hi
I will take a look and get back to you

**Comment by AdaskoTheBeAsT** [comment]
I am not sure yet how much api in VS2022 changed.
As a band aid I exposed full solution path in settings
https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.3.1

**Comment by nfMalde** [comment]
Thanks :-)
