### ISSUE TITLE
Question: Is there a way to create a Nuget Package with the templates and install on the projects?

### ISSUE THREAD

**Issue by luizfbicalho** [AdaskoTheBeAsT/Typewriter#28]
I would like to create nuget packages with my templates and install them in my projects with nuget, this way I would control better the versions and would not need to copu and paste templates everywhere.

Is there a way to do that?

Did anyone try this?

**Comment by AdaskoTheBeAsT** [comment]
https://chat.openai.com/share/e6d0fb78-665f-4fe0-ae8a-761f41cda357
