### ISSUE TITLE
Compatibility with ARM chip

### ISSUE THREAD

**Issue by PI2R** [AdaskoTheBeAsT/Typewriter#31]
Hi,
I have a Windows 11 + visual studio pro 2022 (17.4.3) running within a parralels VM on a mac M1.
I fail to install the latest typewriter release.
Am I missing something or typewriter is just not compatible with an ARM setup?
Thanks in advance for your help with this
Pierre

![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/15934985/86fd0b73-a1e2-484c-a442-6ef99aaac483)

6/7/2023 12:51:10 AM - Microsoft VSIX Installer
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:10 AM - vsixinstaller.exe version:
6/7/2023 12:51:10 AM - 17.5.2046-preview2+g01cdd57f27
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:10 AM - Command line parameters:
6/7/2023 12:51:10 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\Typewriter (1).vsix
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:10 AM - Microsoft VSIX Installer
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:11 AM - Initializing Install...
6/7/2023 12:51:12 AM - Extension Details...
6/7/2023 12:51:12 AM - 	Identifier         : 68E244F1-14E1-4681-A51C-5B902B9EE96C
6/7/2023 12:51:12 AM - 	Name               : Typewriter64
6/7/2023 12:51:12 AM - 	Author             : frhagn
6/7/2023 12:51:12 AM - 	Version            : 2.12.1
6/7/2023 12:51:12 AM - 	Description        : Typewriter generates TypeScript files from c# code files using TypeScript Templates. This allows you to create fully typed TypeScript representations of server side API that automatically updates when you make changes to your c# code.
6/7/2023 12:51:12 AM - 	Locale             : en-US
6/7/2023 12:51:12 AM - 	MoreInfoURL        : http://frhagn.github.io/Typewriter/
6/7/2023 12:51:12 AM - 	InstalledByMSI     : False
6/7/2023 12:51:12 AM - 	SupportedFrameworkVersionRange : [4.7.2,)
6/7/2023 12:51:12 AM - 	SignatureState     : Unsigned
6/7/2023 12:51:12 AM - 	Supported Products : 
6/7/2023 12:51:12 AM - 		Microsoft.VisualStudio.Community
6/7/2023 12:51:12 AM - 			Version : [17.5.3,18.0)
6/7/2023 12:51:12 AM - 			ProductArchitecture : amd64
6/7/2023 12:51:12 AM - 		Microsoft.VisualStudio.Pro
6/7/2023 12:51:12 AM - 			Version : [17.5.3,18.0)
6/7/2023 12:51:12 AM - 			ProductArchitecture : amd64
6/7/2023 12:51:12 AM - 		Microsoft.VisualStudio.Enterprise
6/7/2023 12:51:12 AM - 			Version : [17.5.3,18.0)
6/7/2023 12:51:12 AM - 			ProductArchitecture : amd64
6/7/2023 12:51:12 AM - 	References         : 
6/7/2023 12:51:12 AM - 	Prerequisites      : 
6/7/2023 12:51:12 AM - 		-------------------------------------------------------
6/7/2023 12:51:12 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/7/2023 12:51:12 AM - 		Name         : Visual Studio core editor
6/7/2023 12:51:12 AM - 		Version      : [17.5.3,18.0)
6/7/2023 12:51:12 AM - Signature Details...
6/7/2023 12:51:12 AM - 	Extension is not signed.
6/7/2023 12:51:12 AM - Searching for applicable products...
6/7/2023 12:51:12 AM - Found installed product - Visual Studio Professional 2022
6/7/2023 12:51:12 AM - Found installed product - Visual Studio Professional 2022 Preview
6/7/2023 12:51:12 AM - Found installed product - Global Location
6/7/2023 12:51:12 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by PI2R** [comment]
![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/15934985/86fd0b73-a1e2-484c-a442-6ef99aaac483)

6/7/2023 12:51:10 AM - Microsoft VSIX Installer
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:10 AM - vsixinstaller.exe version:
6/7/2023 12:51:10 AM - 17.5.2046-preview2+g01cdd57f27
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:10 AM - Command line parameters:
6/7/2023 12:51:10 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\Typewriter (1).vsix
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:10 AM - Microsoft VSIX Installer
6/7/2023 12:51:10 AM - -------------------------------------------
6/7/2023 12:51:11 AM - Initializing Install...
6/7/2023 12:51:12 AM - Extension Details...
6/7/2023 12:51:12 AM - 	Identifier         : 68E244F1-14E1-4681-A51C-5B902B9EE96C
6/7/2023 12:51:12 AM - 	Name               : Typewriter64
6/7/2023 12:51:12 AM - 	Author             : frhagn
6/7/2023 12:51:12 AM - 	Version            : 2.12.1
6/7/2023 12:51:12 AM - 	Description        : Typewriter generates TypeScript files from c# code files using TypeScript Templates. This allows you to create fully typed TypeScript representations of server side API that automatically updates when you make changes to your c# code.
6/7/2023 12:51:12 AM - 	Locale             : en-US
6/7/2023 12:51:12 AM - 	MoreInfoURL        : http://frhagn.github.io/Typewriter/
6/7/2023 12:51:12 AM - 	InstalledByMSI     : False
6/7/2023 12:51:12 AM - 	SupportedFrameworkVersionRange : [4.7.2,)
6/7/2023 12:51:12 AM - 	SignatureState     : Unsigned
6/7/2023 12:51:12 AM - 	Supported Products : 
6/7/2023 12:51:12 AM - 		Microsoft.VisualStudio.Community
6/7/2023 12:51:12 AM - 			Version : [17.5.3,18.0)
6/7/2023 12:51:12 AM - 			ProductArchitecture : amd64
6/7/2023 12:51:12 AM - 		Microsoft.VisualStudio.Pro
6/7/2023 12:51:12 AM - 			Version : [17.5.3,18.0)
6/7/2023 12:51:12 AM - 			ProductArchitecture : amd64
6/7/2023 12:51:12 AM - 		Microsoft.VisualStudio.Enterprise
6/7/2023 12:51:12 AM - 			Version : [17.5.3,18.0)
6/7/2023 12:51:12 AM - 			ProductArchitecture : amd64
6/7/2023 12:51:12 AM - 	References         : 
6/7/2023 12:51:12 AM - 	Prerequisites      : 
6/7/2023 12:51:12 AM - 		-------------------------------------------------------
6/7/2023 12:51:12 AM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
6/7/2023 12:51:12 AM - 		Name         : Visual Studio core editor
6/7/2023 12:51:12 AM - 		Version      : [17.5.3,18.0)
6/7/2023 12:51:12 AM - Signature Details...
6/7/2023 12:51:12 AM - 	Extension is not signed.
6/7/2023 12:51:12 AM - Searching for applicable products...
6/7/2023 12:51:12 AM - Found installed product - Visual Studio Professional 2022
6/7/2023 12:51:12 AM - Found installed product - Visual Studio Professional 2022 Preview
6/7/2023 12:51:12 AM - Found installed product - Global Location
6/7/2023 12:51:12 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(IInstallableExtension extension, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by AdaskoTheBeAsT** [comment]
hi - for now this addin is incompatible with VS for Mac - I will need to check the possibility to make extensions which can also work on Mac

**Comment by PI2R** [comment]
Thanks a lot @AdaskoTheBeAsT for your ansxer this is good to know it could be useful inb the future even though I am not yet a big fan of VS for mac.

Just to be clear, today **I am not running VS for mac.**
I am running VS Pro for windows within a windows 11 virtual machine hosted on a MAC. (with an ARM M1 chip)

Does this make a difference around what you need todo to make it work?

Thanks a again, cheers
Pierre

**Comment by AdaskoTheBeAsT** [comment]
experimental release for arm64
https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.24.0

**Comment by PI2R** [comment]
Hi @AdaskoTheBeAsT 
Thank you very much, it is now installing correctly and it seems to be working just fine
Thanks again
Pierre
