### ISSUE TITLE
Guid changes

### ISSUE THREAD

**Issue by Pekafu** [AdaskoTheBeAsT/Typewriter#34]
It seems that since 2.12.0 (added StringLiteralCharacter) there has been one less zero in the Guids, (last part). Doesn't seem intended.

   "\"00000000-0000-0000-0000-000000000000\""
vs                                                                      
"{slc}00000000-0000-0000-0000-00000000000{slc}"

**Comment by AdaskoTheBeAsT** [comment]
thanks a lot! my mistake

fix release in https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.15.0
