### ISSUE TITLE
Why your extension doesn't show on visual studio extensions updates?

### ISSUE THREAD

**Issue by luizfbicalho** [AdaskoTheBeAsT/Typewriter#35]
It would be easier to update in many instalations

**Comment by AdaskoTheBeAsT** [comment]
I know - lack of time - being able to publish something on marketplace requires some page setup and so on etc - right now I do not have too much time for all activities and it usually cost me sleep hours

**Comment by luizfbicalho** [comment]
Is there anything that can help this?

**Comment by AdaskoTheBeAsT** [comment]
no :)
