### ISSUE TITLE
Support for public static readonly fields

### ISSUE THREAD

**Issue by JBBianchi** [AdaskoTheBeAsT/Typewriter#38]
From https://github.com/frhagn/Typewriter/issues/205

> I cannot get public static readonly fields to get picked up by TypeWriter.
> 
> models.tst
> 
> ```
> $Classes(c => c.Name == "SignalRNotifications" || c.Name == "SignalRChannels")[export class $Name {$Fields[
>     static $name: string = '$Value';]}
> ]
> ```
> 
> C# class
> 
> ```
> public static class SignalRNotifications
>     {
>         public static readonly string ImportProgress = "ImportProgressUpdated";
>         public static readonly string ImportCompleted = "ImportCompleted";
>         ...
>     }
> ```

Indeed, for some reason, the static fields are excluded in [RoslynFieldMetadata](https://github.com/AdaskoTheBeAsT/Typewriter/blob/4141289fe5b4d1ac760903d7e2f43036b4f88649/src/Roslyn/RoslynFieldMetadata.cs#L33-L39):
```csharp
public static IEnumerable<IFieldMetadata> FromFieldSymbols(IEnumerable<IFieldSymbol> symbols, Settings settings)
{
    return symbols
        .Where(
            s => s.DeclaredAccessibility == Accessibility.Public && !s.IsConst && !s.IsStatic)
        .Select(s => new RoslynFieldMetadata(s, settings));
}
```

It would be great to be able to opt-in for static members in the settings (and maybe also other more "in-depth" reflection settings like private/protected members ...)

**Comment by JBBianchi** [comment]
I wanted to try to contribute to the project but I can't get it to build in its default state (I had to remove StyleCop and SecurityCodeScan) and all the tests are failing (except one) because `var document = _workspace.CurrentSolution.GetDocumentIdsWithFilePath(path).FirstOrDefault();` returns null.

**Comment by AdaskoTheBeAsT** [comment]
to build you need to have latest VS and also execute submodules-sync.bat

**Comment by AdaskoTheBeAsT** [comment]
and tests works on my machine ;)
![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/1914201/85571f9a-1146-4b63-b9d2-bcdd2e88bb9d)

**Comment by AdaskoTheBeAsT** [comment]
https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.20.0

**Comment by AdaskoTheBeAsT** [comment]
classes and records have StaticReadOnlyFields property which contains collection of such fields (with values)
