### ISSUE TITLE
(Almost) unable to build project

### ISSUE THREAD

**Issue by JBBianchi** [AdaskoTheBeAsT/Typewriter#39]
I cloned the project and ran [submodules-sync.bat](https://github.com/AdaskoTheBeAsT/Typewriter/blob/master/submodules-sync.bat) but the later didn't do anything.

I then cloned the sub repos ([Buildalyzer and then marvin) and checked them out at their specific commit. I ended up with a missing file error: `...\Typewriter\stylecop.json' could not be found.` (where `Typewriter` is the root of the git repo).

I copied the one I found in Buildalyzer, the build was successful but still with analyzer errors.

**Comment by AdaskoTheBeAsT** [comment]
submodules-sync should work - please be aware that I use my custom build Buildalyzer (due to fact that i need to set framewokr to net472 to be able to work with VS) in specific branch
https://github.com/AdaskoTheBeAsT/Buildalyzer/tree/feature/typewriter

**Comment by JBBianchi** [comment]
**should** is indeed the right term, in my case it doesn't:
```
PS C:\Dev\Sandbox> git clone https://github.com/AdaskoTheBeAsT/Typewriter.git Typewriter_demo
Cloning into 'Typewriter_demo'...
remote: Enumerating objects: 6477, done.
remote: Counting objects: 100% (1222/1222), done.
remote: Compressing objects: 100% (425/425), done.
Receiving objects: 100% (6477/6477), 8.17 MiB | 26.07 MiB/s, done.ed 5255

Resolving deltas: 100% (4602/4602), done.
PS C:\Dev\Sandbox> cd .\Typewriter_demo\
PS C:\Dev\Sandbox\Typewriter_demo> .\submodules-sync.bat

C:\Dev\Sandbox\Typewriter_demo>git submodule update --remote --merge
PS C:\Dev\Sandbox\Typewriter_demo> dir .\Buildalyzer\
PS C:\Dev\Sandbox\Typewriter_demo>
```

**Comment by AdaskoTheBeAsT** [comment]
Which version of git do you have? I always install original latest one
besides that builtin into vs

sob., 16 gru 2023, 09:12 użytkownik Jean-Baptiste Bianchi <
***@***.***> napisał:

**Comment by JBBianchi** [comment]
I'm using the latest git for windows:
```
PS C:\Dev\Sandbox\Typewriter_demo> git --version
git version 2.43.0.windows.1
```

**Comment by AdaskoTheBeAsT** [comment]
as I checked everything is working correctly when cloning - bat file should be launched in regular command line not powershell
