### ISSUE TITLE
File-scoped namespace declaration

### ISSUE THREAD

**Issue by mira-matze** [AdaskoTheBeAsT/Typewriter#4]
Template rendering does not work when using file-scoped namespace declaration of C# 10.

**Comment by AdaskoTheBeAsT** [comment]
I will check this

**Comment by AdaskoTheBeAsT** [comment]
Ok finally found easy way to do this.
Released in https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.5.0

**Comment by mira-matze** [comment]
Works great! Thanks a lot.

**Comment by SamuelKupferschmid** [comment]
Thank you so much! Our Team was waiting for it. Now we can drop VS2019
