### ISSUE TITLE
Support of Visual Studio 2022

### ISSUE THREAD

**Issue by Jareco** [AdaskoTheBeAsT/Typewriter#42]
Hi, will you add a Visual Studio 2022 support? Unfortunately, the current release doesnt't support it: 

Install log:

01.03.2024 20:08:32 - Microsoft VSIX Installer
01.03.2024 20:08:32 - -------------------------------------------
01.03.2024 20:08:32 - vsixinstaller.exe version:
01.03.2024 20:08:32 - 17.7.2196+2d27ec4064
01.03.2024 20:08:32 - -------------------------------------------
01.03.2024 20:08:32 - Command line parameters:
01.03.2024 20:08:32 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\Vitalii.Romanov\Downloads\Typewriter.vsix
01.03.2024 20:08:32 - -------------------------------------------
01.03.2024 20:08:32 - Microsoft VSIX Installer
01.03.2024 20:08:32 - -------------------------------------------
01.03.2024 20:08:32 - Initializing Install...
01.03.2024 20:08:32 - Er wird nach passenden Produkten gesucht...
01.03.2024 20:08:32 - Installiertes Produkt gefunden - Visual Studio Professional 2022
01.03.2024 20:08:32 - Installiertes Produkt gefunden - Visual Studio Professional 2019
01.03.2024 20:08:32 - Installiertes Produkt gefunden - Globaler Pfad
01.03.2024 20:08:32 - Erweiterungsdetails...
01.03.2024 20:08:32 - 	Identifier         : 68E244F1-14E1-4681-A51C-5B902B9EE96C
01.03.2024 20:08:32 - 	Name               : Typewriter64
01.03.2024 20:08:32 - 	Author             : frhagn
01.03.2024 20:08:32 - 	Version            : 2.26.0
01.03.2024 20:08:32 - 	Description        : Typewriter generates TypeScript files from c# code files using TypeScript Templates. This allows you to create fully typed TypeScript representations of server side API that automatically updates when you make changes to your c# code.
01.03.2024 20:08:32 - 	Locale             : en-US
01.03.2024 20:08:32 - 	MoreInfoURL        : http://frhagn.github.io/Typewriter/
01.03.2024 20:08:32 - 	InstalledByMSI     : False
01.03.2024 20:08:32 - 	SupportedFrameworkVersionRange : [4.7.2,)
01.03.2024 20:08:33 - 	SignatureState     : Unsigned
01.03.2024 20:08:33 - 	Unterstützte Produkte : 
01.03.2024 20:08:33 - 		Microsoft.VisualStudio.Community
01.03.2024 20:08:33 - 			Version : [17.8.4,18.0)
01.03.2024 20:08:33 - 			ProductArchitecture : amd64
01.03.2024 20:08:33 - 		Microsoft.VisualStudio.Community
01.03.2024 20:08:33 - 			Version : [17.8.4,18.0)
01.03.2024 20:08:33 - 			ProductArchitecture : arm64
01.03.2024 20:08:33 - 		Microsoft.VisualStudio.Pro
01.03.2024 20:08:33 - 			Version : [17.8.4,18.0)
01.03.2024 20:08:33 - 			ProductArchitecture : amd64
01.03.2024 20:08:33 - 		Microsoft.VisualStudio.Pro
01.03.2024 20:08:33 - 			Version : [17.8.4,18.0)
01.03.2024 20:08:33 - 			ProductArchitecture : arm64
01.03.2024 20:08:33 - 		Microsoft.VisualStudio.Enterprise
01.03.2024 20:08:33 - 			Version : [17.8.4,18.0)
01.03.2024 20:08:33 - 			ProductArchitecture : amd64
01.03.2024 20:08:33 - 		Microsoft.VisualStudio.Enterprise
01.03.2024 20:08:33 - 			Version : [17.8.4,18.0)
01.03.2024 20:08:33 - 			ProductArchitecture : arm64
01.03.2024 20:08:33 - 	Verweise           : 
01.03.2024 20:08:33 - 	Voraussetzungen    : 
01.03.2024 20:08:33 - 		-------------------------------------------------------
01.03.2024 20:08:33 - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
01.03.2024 20:08:33 - 		Name         : Visual Studio core editor
01.03.2024 20:08:33 - 		Version      : [17.8.4,18.0)
01.03.2024 20:08:33 - Signaturdetails...
01.03.2024 20:08:33 - 	Extension is not signed.
01.03.2024 20:08:33 - VSIXInstaller.NoApplicableSKUsException: Diese Erweiterung kann auf den derzeit installierten Produkten nicht installiert werden.
   bei VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:Zeile 186.
   bei VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:Zeile 28.
   bei VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:Zeile 101.
   bei VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:Zeile 42.
   bei VSIXInstaller.App.Initialize(Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:Zeile 272.
   bei VSIXInstaller.App.Initialize() in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:Zeile 230.
   bei System.Threading.Tasks.Task`1.InnerInvoke()
   bei System.Threading.Tasks.Task.Execute()

**Comment by AdaskoTheBeAsT** [comment]
hi did you checked this one? https://github.com/AdaskoTheBeAsT/Typewriter/releases/tag/v2.26.0

**Comment by Jareco** [comment]
Yes. Sorry, it's in German:
![image](https://github.com/AdaskoTheBeAsT/Typewriter/assets/23664185/e113b0c9-708d-4978-b0a5-cfe1b70adcdc)


Could it be because I have multiple instances of Visual Studio (VS 2019 and VS2022)? When I'm installing an original Typewriter, it finds the version VS2019 because it supports it.

**Comment by Fasteroid** [comment]
Reproduced.
[dd_VSIXInstaller_20240408111743_80ec.log](https://github.com/AdaskoTheBeAsT/Typewriter/files/14907489/dd_VSIXInstaller_20240408111743_80ec.log)

**Comment by Fasteroid** [comment]
Oops.  Looks like I needed to update!
