### ISSUE TITLE
Build error:  Source file 'Typewriter\stylecop.json' could not be found.

### ISSUE THREAD

**Issue by Fasteroid** [AdaskoTheBeAsT/Typewriter#43]
Seems to be missing from the project... can't build correctly without it.

**Comment by Fasteroid** [comment]
Stylecop seems deliberately impossible to remove.  How am I supposed to build this or work on it?

**Comment by AdaskoTheBeAsT** [comment]
not sure how it happened - fixed

**Comment by Fasteroid** [comment]
I'll try building it again... one moment.

**Comment by Fasteroid** [comment]
Aside from having a few thousand style-related warnings, it builds now.  Thank you!
