### ISSUE TITLE
Cannot find project named XX.XX

### ISSUE THREAD

**Issue by blazing-panda** [AdaskoTheBeAsT/Typewriter#49]
I am experiencing a problem with the Typewriter extension, where I can render files exactly once before I need to restart Visual Studio 2022 for our existing project.
None of my coworkers is experiencing the same issue with the exact same versions of the extension and Visual Studio (17.10.4).

# Behaviour

I start Visual Studio and render my template. 
This works everything renders as expected.
However, when I now try to render the template a second time, it says `WARNING: Cannot find project named 'XX.XX'` 

# What I looked into

I looked into the source code, and this seems to occur in ProjectHelpers.AddProject where it apparently cant find the project in the `ProjectItem.DTE.Solution.AllPreojects()`. 
My guess is that for some reason the extension unloads the Projects after the first render, though I can not find out why this happens.

Also for changed files, the extension reports: `WARNING: Failed to save source map for 'AbsolutPathToFile\File.cs'. Project type not supported.` Which should have something to do with how the files are added to the `.csproj` file. but I do not know why it cant sace them, this is a snippet from the `,proj` file:

```xml
 <ItemGroup>
   <None Update="Scripts\Shared\Vms\Generated\Color.ts">
     <CustomToolNamespace>..\Project\Enums\Color.cs</CustomToolNamespace>
   </None>
.....
````

If I could provide more Information, please let me know :)

For now, my only solution is to restart Visual Studio when I need to render the template Xx

**Comment by AdaskoTheBeAsT** [comment]
hi,

can you please set option responsible for adding things to csproj to false?
in new sdk based project it is not necessary

![image](https://github.com/user-attachments/assets/db1fb040-33c0-4884-823c-a56d352d305a)

**Comment by blazing-panda** [comment]
Thanks, this seems to fix my problem.
I changed the setting and then restarted Visual Studio. Without restarting Visual Studio it did not work.

My coworkers have the setting enabled without any trouble though.

I do still get some errors during rendering, but this does not seem to actually prevent anything from rendering
```
WARNING: Template  will be ignored until the errors are removed.
ERROR: Cannot find path of project item Object reference not set to an instance of an object.
ERROR: Cannot find path of project item Object reference not set to an instance of an object.
````

I am using:
* Typewriter: 2.31.0
* Visual Studio 2022: 17.11.0 (just updated this though 17.10.6 before)

**Comment by blazing-panda** [comment]
I tried to activate it again and now it seems to work even if I keep it activated

**Comment by AdaskoTheBeAsT** [comment]
not sure - maybe that clean install fixed the problem
